apiVersion: v1
kind: Pod
metadata:
  name: nodeapp-pod
  labels:
    name: nodeapp
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: krishnu121/testimage:test
      ports:
        - containerPort: 80
