apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  labels:
    name: nodeapp-service
    app: nodeapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: nodeapp
    app: nodeapp
